pipeline {
    agent any 
    stages {
        stage('Git Clone') { 
            steps {
                git branch: 'main', credentialsId: 'b032d43a-9ab4-4b05-9e35-b3be11a25d2f', url: 'https://github.com/neerajaggarwal2501/selenium.git'
            }
        }
        stage('execute tests using maven') { 
            steps {
                bat 'mvn -f 25082023/pom.xml clean test'
            }
        }
        stage('Publish Test Report in Jenkins') { 
            steps {
                cucumber buildStatus: 'UNCHANGED', customCssFiles: '', customJsFiles: '', failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: '**/TestReport.json', jsonReportDirectory: '25082023/TestReports', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1 
            }
        }
    }
}
